var express=require("express");
var app=express();
var router=require("./router");
var bodyParser=require("body-parser");
app.use("/",function(req,res,next){
	res.header({"Access-Control-Allow-Origin":"*"});
	next();
});
app.use(express.static("static"));
app.use(bodyParser.urlencoded({extended:false}));
app.post("/login",router.login);
app.post("/register",router.register);
app.post("/check",router.check);
app.post("/findByType",router.findByType);
app.post("/downLoadGame",router.downLoadGame);
app.post("/findList",router.findList);
app.post("/findMyDownload",router.findMyDownload);
app.post("/findGameInfo",router.findGameInfo);
app.post("/findDifferentGame",router.findDifferentGame);
app.post("/addAttention",router.addAttention);
app.post("/findMyAttention",router.findMyAttention);
app.post("/orderGame",router.orderGame);
app.post("/findMyOrder",router.findMyOrder);
app.post("/findPost",router.findPost);
app.post("/findPostInfo",router.findPostInfo);
app.post("/findPostCommit",router.findPostCommit);
app.post("/findGameCommit",router.findGameCommit);
app.post("/addPostCommit",router.addPostCommit);
app.post("/addGameCommit",router.addGameCommit);
app.post("/addPostGood",router.addPostGood);
app.post("/addGameGood",router.addGameGood);
app.listen(3000);
